### ISSUE TITLE
현행 기술 파악

### ISSUE THREAD

**Issue by pyowonil** [pyowonil/ConvertSoundToScore#2]
형식 : 기술명 ( 링크 주소 ) - 간단한 설명

**Comment by pyowonil** [comment]
Control Speed ( http://www.seventhstring.com/resources/slowdown.html ; http://www.pianoclues.com/wordpress/2008/03/05/how-to-convert-mp3-or-wav-file-to-midi-or-sheet-music/ ) -
1. 단일 악기에 대한 연주라 할지라도 빠르게 연주되거나 화음이 존재하면 복잡해진다
2. 천천히 듣는것이 transcribing 하기 편하다.

> 기술에대한 명칭과 자세한 설명은 없지만 위의 링크를 통해 속도를 조절하는 기능이 필요한것 같다.

**Comment by pyowonil** [comment]
Fast Fourier Transform ( https://en.wikipedia.org/wiki/Fast_Fourier_transform ) - 
1. Time domain -> Frequence Domain
2. Complexity of computing DFT : O(n^2) -> Complexity of computing FFT : O(n log(n))

**Comment by parkbogyu** [comment]
Wavelet Transform - Fourier Transform의 단점을 보완한 방법

links
< Wavelet 이란? >
- https://ko.wikipedia.org/wiki/%EC%9B%A8%EC%9D%B4%EB%B8%94%EB%A6%BF_%EB%B3%80%ED%99%98
- http://blog.naver.com/dhlion/20012559855
- http://cfd.hanyang.ac.kr/research/research_kor_wavelets.htm
- http://www.potatogim.net/wiki/%EC%9B%A8%EC%9D%B4%EB%B8%94%EB%A6%BF_%EB%B3%80%ED%99%98
- http://vlsi.catholic.ac.kr/research/research-11.html
- http://clavez.tistory.com/54
- http://blog.naver.com/ichitaka99/90014767560

< 고역 통과 필터 >
- http://realheart.egloos.com/2219537
- 저역 통과 필터는 위와 반대

< wavelet transform source code example >
- http://201114006.tistory.com/60
- http://www.bearcave.com/misl/misl_tech/wavelets/packet/download.html
