### ISSUE TITLE
하이브리드앱(폰갭) 조사내용

### ISSUE THREAD

**Issue by pyowonil** [pyowonil/ConvertSoundToScore#3]
형식 : ( 링크 주소 ) - 간단한 내용

**Comment by JJHun** [comment]
아니

**Comment by pyowonil** [comment]
( http://d2.naver.com/helloworld/8180 ) - PhoneGap 을 이용한 앱 개발

**Comment by pyowonil** [comment]
( https://ko.wikipedia.org/wiki/%ED%8F%B0%EA%B0%AD ) - wiki(한글) 폰갭

**Comment by pyowonil** [comment]
( http://phonegap.com/ ) - 폰갭 홈페이지

**Comment by pyowonil** [comment]
( http://qnibus.com/blog/phonegap-3-0-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95/ ) - 폰갭 3.0 사용 방법

**Comment by pyowonil** [comment]
( http://docs.phonegap.com/en/1.5.0/index.html ) - 폰갭 API

**Comment by pyowonil** [comment]
( http://hojeong.tistory.com/31 ) - 폰갭 설치 (Windows)

**Comment by parkbogyu** [comment]
폰갭 환경설정 및 구동법
시뮬레이터 실행 시 오래걸리므로 금방 끄지 말것 ㅋㅋ
< 시뮬 생성법(폰갭 설치법도 포함) >
- http://www.slideshare.net/kimgura/phonegap-37455492

< 폰갭 설치 및 구동법 >
- https://ujeani.wordpress.com/2011/09/02/002/
