### ISSUE TITLE
데이터 구조 조사 ( MusicXML, NIFF, MIDI, ..., etc. )

### ISSUE THREAD

**Issue by pyowonil** [pyowonil/ConvertSoundToScore#5]

**Comment by JJHun** [comment]
1. Generating simple MIDI files using Java, without using the Java Sound API 
  - 링크 : http://kevinboone.net/javamidi.html
  - MIDI file의 대략적인 구조, JAVA로 midi 파일 생성 방법
  - 안드로이드에서 MIDI

2. MIDI 파일 구조에서 참고할 사항
 - 링크 : http://camomiles.tistory.com/28
 - 링크 안의 링크는 잘못된 링크들임
 - HEADCHUNK, Track, Tick, delta time, variable length 저장방식

**Comment by JJHun** [comment]
4. JAVA SOUND 관련  ( MIDI )
 http://www.jsresources.org/faq_midi.html
 http://docs.oracle.com/javase/1.5.0/docs/guide/sound/programmer_guide/contents.html
